load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_binary(
    name = "microgpt",
    srcs = [
        "src/infer.rs",
        "src/main.rs",
        "src/train.rs",
    ],
    crate_features = select({
        "//:is_mac": ["metal"],
        "//conditions:default": [],
    }),
    crate_name = "microgpt_cli",
    deps = [
        "//domains/ai/libs/microgpt",
    ] + all_crate_deps(cargo_only = True),
)

rust_test(
    name = "test_microgpt_cli",
    size = "small",
    crate = ":microgpt",
)
