bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "container_structure_test", version = "1.22.1")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")
oci.pull(
    name = "docker_lib_ubuntu",
    digest = "sha256:513c074113a871b51a8d16ab445c88779d6452d937a164fb5cc479f32668a41d",
    image = "docker.io/library/ubuntu",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
oci.pull(
    name = "java_base",
    digest = "sha256:b782b1d4fb2064f97044c1ee658bbaa4e688a4caf06bbe04acaec0279727df7e",
    image = "docker.io/azul/zulu-openjdk",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
    tag = "25",
)
oci.pull(
    name = "distroless_base",
    digest = "sha256:fabbf1c0c357a3d42550111351daed089b20a2c954df13ee2fcff60602515e84",
    image = "gcr.io/distroless/base-debian12",
    platforms = [
        "linux/amd64",
        "linux/arm64/v8",
    ],
)
use_repo(oci, "distroless_base", "distroless_base_linux_amd64", "distroless_base_linux_arm64_v8", "docker_lib_ubuntu", "docker_lib_ubuntu_linux_amd64", "docker_lib_ubuntu_linux_arm64_v8", "java_base", "java_base_linux_amd64", "java_base_linux_arm64_v8")
