java_library(
    name = "json",
    srcs = glob(["*.java"]),
    deps = [
      "@maven//:com_fasterxml_jackson_core_jackson_core",
      "@maven//:com_fasterxml_jackson_core_jackson_databind",
      "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jdk8",
      "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_guava",
      "@maven//:com_fasterxml_jackson_datatype_jackson_datatype_jsr310",
    ],
    visibility = ["//visibility:public"],
)
