use opentelemetry::{global, KeyValue};
use opentelemetry::metrics::{Counter, Histogram};

pub struct AppMetrics {
    pub requests_total: Counter<u64>,
    pub tokens_generated_total: Counter<u64>,
    pub conversations_total: Counter<u64>,
    pub request_duration_ms: Histogram<f64>,
    pub tokens_per_second: Histogram<f64>,
}

impl AppMetrics {
    pub fn new() -> Self {
        let meter = global::meter("microgpt");
        AppMetrics {
            requests_total: meter
                .u64_counter("microgpt_requests")
                .with_description("Total inference requests by endpoint")
                .build(),
            tokens_generated_total: meter
                .u64_counter("microgpt_tokens_generated")
                .with_description("Total tokens generated by endpoint")
                .build(),
            conversations_total: meter
                .u64_counter("microgpt_conversations")
                .with_description("Total chat conversations handled")
                .build(),
            request_duration_ms: meter
                .f64_histogram("microgpt_request_duration_ms")
                .with_description("Inference request duration in milliseconds")
                .with_unit("ms")
                .build(),
            tokens_per_second: meter
                .f64_histogram("microgpt_tokens_per_second")
                .with_description("Tokens generated per second per request")
                .build(),
        }
    }

    pub fn record_generate(&self, tokens: u64, duration_ms: f64) {
        let attrs = [KeyValue::new("endpoint", "generate")];
        let tps = if duration_ms > 0.0 {
            tokens as f64 / (duration_ms / 1000.0)
        } else {
            0.0
        };
        self.requests_total.add(1, &attrs);
        self.tokens_generated_total.add(tokens, &attrs);
        self.request_duration_ms.record(duration_ms, &attrs);
        self.tokens_per_second.record(tps, &attrs);
    }

    pub fn record_chat(&self, tokens: u64, duration_ms: f64) {
        let attrs = [KeyValue::new("endpoint", "chat")];
        let tps = if duration_ms > 0.0 {
            tokens as f64 / (duration_ms / 1000.0)
        } else {
            0.0
        };
        self.requests_total.add(1, &attrs);
        self.conversations_total.add(1, &[]);
        self.tokens_generated_total.add(tokens, &attrs);
        self.request_duration_ms.record(duration_ms, &attrs);
        self.tokens_per_second.record(tps, &attrs);
    }
}
