use opentelemetry::metrics::{Counter, Meter};
use opentelemetry::{KeyValue, global};

/// The `endpoint` label values the emit sites use — the whole set, because a
/// zero baseline is per series and a series is the instrument *and* its
/// attributes. Spelled out rather than derived so a third endpoint has to say
/// so here too.
const ENDPOINTS: [&str; 2] = ["generate", "chat"];

pub struct AppMetrics {
    pub requests_total: Counter<u64>,
    pub tokens_generated_total: Counter<u64>,
    pub conversations_total: Counter<u64>,
    pub inference_ms_total: Counter<f64>,
}

impl AppMetrics {
    pub fn new() -> Self {
        Self::with_meter(&global::meter("microgpt"))
    }

    /// Takes the meter rather than reaching for the global one so a test can
    /// hand it an isolated provider and read the exported series back.
    pub fn with_meter(meter: &Meter) -> Self {
        let metrics = AppMetrics {
            requests_total: meter
                .u64_counter("microgpt_requests")
                .with_description("Total inference requests by endpoint")
                .build(),
            tokens_generated_total: meter
                .u64_counter("microgpt_tokens_generated")
                .with_description("Total tokens generated by endpoint")
                .build(),
            conversations_total: meter
                .u64_counter("microgpt_conversations")
                .with_description("Total chat conversations handled")
                .build(),
            // A counter of milliseconds, not a histogram of durations (#1384):
            // every consumer of the old microgpt_request_duration_ms histogram
            // read only its _sum and _count, and a histogram cannot be put on
            // the wire at zero without biasing exactly that ratio — record(0.0)
            // adds an observation. Two zero-declarable counters carry the same
            // answer: mean duration is rate(inference_ms)/rate(requests), and
            // tokens per second of inference is rate(tokens)/rate(inference_ms).
            inference_ms_total: meter
                .f64_counter("microgpt_inference_ms")
                .with_description("Cumulative inference time in milliseconds by endpoint")
                .build(),
        };
        metrics.declare();
        metrics
    }

    /// Puts every series on the wire at 0 before anything is served (#1323).
    /// Building the instrument is not enough: the SDK exports nothing for an
    /// instrument that has taken no measurement, so without this each series
    /// is born carrying its first request's value and `increase()` has no
    /// earlier sample to measure it against — the first generate after every
    /// deploy is uncounted, forever.
    ///
    /// Adding zero is what materializes the series. Zero is a measurement,
    /// and for a counter it is also the identity — which is why this rail
    /// carries counters only (see inference_ms_total above).
    fn declare(&self) {
        self.conversations_total.add(0, &[]);
        for endpoint in ENDPOINTS {
            let attrs = [KeyValue::new("endpoint", endpoint)];
            self.requests_total.add(0, &attrs);
            self.tokens_generated_total.add(0, &attrs);
            self.inference_ms_total.add(0.0, &attrs);
        }
    }

    pub fn record_generate(&self, tokens: u64, duration_ms: f64) {
        let attrs = [KeyValue::new("endpoint", "generate")];
        self.requests_total.add(1, &attrs);
        self.tokens_generated_total.add(tokens, &attrs);
        self.inference_ms_total.add(duration_ms, &attrs);
    }

    pub fn record_chat(&self, tokens: u64, duration_ms: f64) {
        let attrs = [KeyValue::new("endpoint", "chat")];
        self.requests_total.add(1, &attrs);
        self.conversations_total.add(1, &[]);
        self.tokens_generated_total.add(tokens, &attrs);
        self.inference_ms_total.add(duration_ms, &attrs);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use opentelemetry::metrics::MeterProvider as _;
    use opentelemetry_sdk::metrics::data::{AggregatedMetrics, MetricData, ResourceMetrics};
    use opentelemetry_sdk::metrics::{InMemoryMetricExporter, PeriodicReader, SdkMeterProvider};

    struct Rig {
        provider: SdkMeterProvider,
        exporter: InMemoryMetricExporter,
        metrics: AppMetrics,
    }

    /// An isolated provider, so this reads only what AppMetrics recorded — the
    /// global one is shared with whatever else the test binary touched.
    fn rig() -> Rig {
        let exporter = InMemoryMetricExporter::default();
        let provider = SdkMeterProvider::builder()
            .with_reader(PeriodicReader::builder(exporter.clone()).build())
            .build();
        let metrics = AppMetrics::with_meter(&provider.meter("microgpt"));
        Rig {
            provider,
            exporter,
            metrics,
        }
    }

    fn exported(rig: &Rig) -> ResourceMetrics {
        rig.provider.force_flush().expect("force_flush failed");
        rig.exporter
            .get_finished_metrics()
            .expect("get_finished_metrics failed")
            .pop()
            .expect("nothing was exported")
    }

    /// `name{endpoint="..."}` and its value, for EVERY counter series the
    /// export carries — u64 and f64 sums alike, not a lookup by name. Sweeping
    /// the whole export is what makes an unexpected series fail: a by-name
    /// reader can only check the instruments the test already thought to ask
    /// about, so a counter added with no entry in `declare()` would slip past
    /// it exactly the way this whole change exists to prevent.
    ///
    /// A series missing entirely simply does not appear — the SDK exports
    /// nothing for an instrument that has taken no measurement, which is the
    /// bug being pinned.
    fn counter_series(rm: &ResourceMetrics) -> Vec<(String, f64)> {
        let mut out = vec![];
        for scope in rm.scope_metrics() {
            for metric in scope.metrics() {
                let mut push = |attrs: Vec<(String, String)>, value: f64| {
                    let label = match attrs.iter().find(|(key, _)| key == "endpoint") {
                        Some((_, endpoint)) => {
                            format!("{}{{endpoint=\"{}\"}}", metric.name(), endpoint)
                        }
                        None => metric.name().to_string(),
                    };
                    out.push((label, value));
                };
                match metric.data() {
                    AggregatedMetrics::U64(MetricData::Sum(sum)) => {
                        for dp in sum.data_points() {
                            let attrs = dp
                                .attributes()
                                .map(|kv| (kv.key.to_string(), kv.value.to_string()))
                                .collect();
                            push(attrs, dp.value() as f64);
                        }
                    }
                    AggregatedMetrics::F64(MetricData::Sum(sum)) => {
                        for dp in sum.data_points() {
                            let attrs = dp
                                .attributes()
                                .map(|kv| (kv.key.to_string(), kv.value.to_string()))
                                .collect();
                            push(attrs, dp.value());
                        }
                    }
                    _ => {}
                }
            }
        }
        out.sort_by(|a, b| a.0.cmp(&b.0));
        out
    }

    /// The seven series `declare()` is expected to produce: the five counts at
    /// `count` and the two duration sums at `generate_ms`/`chat_ms`.
    fn expected(count: f64, generate_ms: f64, chat_ms: f64) -> Vec<(String, f64)> {
        let mut out = vec![
            ("microgpt_conversations".to_string(), count),
            (r#"microgpt_inference_ms{endpoint="chat"}"#.to_string(), chat_ms),
            (
                r#"microgpt_inference_ms{endpoint="generate"}"#.to_string(),
                generate_ms,
            ),
            (r#"microgpt_requests{endpoint="chat"}"#.to_string(), count),
            (
                r#"microgpt_requests{endpoint="generate"}"#.to_string(),
                count,
            ),
            (
                r#"microgpt_tokens_generated{endpoint="chat"}"#.to_string(),
                count,
            ),
            (
                r#"microgpt_tokens_generated{endpoint="generate"}"#.to_string(),
                count,
            ),
        ];
        out.sort_by(|a, b| a.0.cmp(&b.0));
        out
    }

    /// The zero baseline (#1323). Every series must be on the wire at 0 from
    /// construction, before a single request — otherwise it is born carrying
    /// its first request's value and increase() shows nothing for that
    /// request, ever.
    ///
    /// Compared as a whole set, so this fails on a missing series, an extra
    /// one, and a nonzero one alike.
    #[test]
    fn building_the_metrics_declares_every_counter_series_at_zero() {
        let rig = rig();
        assert_eq!(counter_series(&exported(&rig)), expected(0.0, 0.0, 0.0));
    }

    /// The declared set and the emit sites have to agree, or a declared
    /// endpoint nobody serves is a permanently flat line and a served one
    /// nobody declared loses its first request. Serving both endpoints once
    /// must land on exactly the declared series and nothing else.
    #[test]
    fn recording_adds_no_series_the_declaration_did_not_cover() {
        let rig = rig();
        rig.metrics.record_generate(1, 100.0);
        rig.metrics.record_chat(1, 50.0);

        // One request each, one token each, one conversation, and each
        // endpoint's milliseconds — every series lands on a declared name.
        assert_eq!(
            counter_series(&exported(&rig)),
            expected(1.0, 100.0, 50.0)
        );
    }

    /// The whole rail is counters (#1384): a histogram cannot be declared at
    /// zero — record(0.0) is an observation that biases rate(_sum)/rate(_count)
    /// — so nothing here may export one. The two counter tests above are this
    /// test's positive control: the export is provably non-empty, so an empty
    /// histogram list means "none exist", not "nothing was read".
    #[test]
    fn nothing_exports_with_a_first_observation_gap() {
        let rig = rig();
        rig.metrics.record_generate(1, 100.0);
        rig.metrics.record_chat(1, 50.0);
        let rm = exported(&rig);
        for scope in rm.scope_metrics() {
            for metric in scope.metrics() {
                assert!(
                    matches!(
                        metric.data(),
                        AggregatedMetrics::U64(MetricData::Sum(_))
                            | AggregatedMetrics::F64(MetricData::Sum(_))
                    ),
                    "{} exports a non-counter aggregation, which cannot carry a zero baseline",
                    metric.name()
                );
            }
        }
    }
}
