# load("@rules_scala//scala:scala.bzl", "scala_binary")

# scala_binary(
#     name = "ray_tracer",
#     srcs = [
#         "App.scala",
#     ],
#     main_class = "com.muchq.scraphics.App",
#     visibility = ["//visibility:public"],
#     deps = [
#         "//domains/graphics/libs/scraphics/tracer",
#         "@maven//:org_slf4j_slf4j_api",
#     ],
# )
