java_library(
    name = "utils",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@third_party//com/fasterxml/jackson/core:jackson_annotations",
        "@third_party//com/fasterxml/jackson/core:jackson_core",
        "@third_party//com/fasterxml/jackson/core:jackson_databind",
        "@third_party//com/fasterxml/jackson/datatype:jackson_datatype_guava",
        "@third_party//com/fasterxml/jackson/datatype:jackson_datatype_jdk8",
        "@third_party//com/fasterxml/jackson/datatype:jackson_datatype_jsr310",
        "@third_party//com/google/guava",
    ],
)
