java_library(
    name = "lib",
    srcs = glob(["*.java"]),
    deps = [
      "@maven//:io_netty_netty_common",
      "@maven//:io_netty_netty_handler",
      "@maven//:io_netty_netty_transport",
      "@maven//:io_netty_netty_codec",
      "@maven//:org_slf4j_slf4j_api",
    ],
    visibility = ["//visibility:public"],
)
