java_library(
    name = "lib",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "@third_party//io/netty:netty_buffer",
        "@third_party//io/netty:netty_codec",
        "@third_party//io/netty:netty_common",
        "@third_party//io/netty:netty_handler",
        "@third_party//io/netty:netty_transport",
        "@third_party//org/slf4j:slf4j_api",
    ],
)
