#!/usr/bin/env python3
"""Rebuilds tactics_corpus.pgn from public chess.com archives.

Why a second corpus at all: hikaru_corpus.pgn (500 games, one player, June
2026, blitz + bullet) is a wide net over *ordinary* play. Ordinary play is
mostly resignations in the middlegame, so the moves that break a replayer —
underpromotion, en passant, castling into a mate, disambiguation under
check — barely appear in it. One archive of 709 games held a single
underpromotion.

So this bank is selected, not sampled. It draws from a different player set
than hikaru_corpus (no overlap, deliberately: two banks that agree because
they contain the same games prove nothing), and it keeps only games carrying
at least one edge case, rarest first. The result is small and dense where the
other is large and representative.

Selection is by tier, and every tier is a *textual* match on the movetext —
no board is replayed here on purpose. The corpus is an oracle for the
replayer, so it must not be built by the thing it checks. En passant has no
SAN marker and so cannot be selected for; it arrives incidentally, and
corpus_test asserts how much of it actually landed rather than trusting that
it did.

    tier 1  odds game                 [SetUp "1"] + a starting [FEN]
    tier 2  underpromotion            =N  =R  =B
    tier 3  promotion giving check    =Q+  =N#  ...
    tier 4  checkmate                 #
    tier 5  long game                 >= 100 plies

Tier 1 is the odd one out, and is a header match rather than a movetext
match: chess.com serves "odds" games, where one player spots the other a
piece, with the starting position in a [FEN] header. They are the only
games in either bank that do not start from the standard position, so they
are the only thing exercising ReplayFrom() — and a replayer that assumes
the standard start reads their moves as illegal rather than as a different
game. They are selected for, not left to chance, because corpus_test
asserts the bank still has some.

Each game carries chess.com's own [CurrentPosition] header, which is what
makes the bank self-checking: the final FEN after replay must equal the
header the server wrote. No golden file, nothing generated by our own code.

Usage:  python3 build_tactics_corpus.py > tactics_corpus.pgn

Rerunning will not reproduce this file byte for byte — archives grow as
players play. That is fine; the test asserts coverage floors, not a fixed
list. Bump the caps if a rebuild comes back thin.
"""

import json
import re
import sys
import time
import urllib.error
import urllib.request

USER_AGENT = "MoonBase-corpus-builder/1.0 (https://github.com/muchq/MoonBase)"

# Public archives, chosen for tactical density and for having no player in
# common with hikaru_corpus.pgn.
ARCHIVES = [
    ("gothamchess", 2026, 5),
    ("gothamchess", 2026, 4),
    ("nihalsarin", 2026, 5),
]

TOTAL_CAP = 150
PER_ARCHIVE_CAP = 60

UNDERPROMOTION = re.compile(r"=[NRB]")
PROMOTION_CHECK = re.compile(r"=[QNRB][+#]")
MATE = re.compile(r"#")
LONG_GAME = re.compile(r"\b(?:[5-9][0-9]|[1-9][0-9]{2,})\.")
COMMENT = re.compile(r"\{[^}]*\}")


def tier(pgn: str, movetext: str) -> int:
    """Lower is rarer. 0 means the game carries nothing worth keeping."""
    if '[SetUp "1"]' in pgn:
        return 1
    if UNDERPROMOTION.search(movetext):
        return 2
    if PROMOTION_CHECK.search(movetext):
        return 3
    if MATE.search(movetext):
        return 4
    # A move number of 50 or more, i.e. at least 99 plies. Matched against
    # comment-stripped movetext: chess.com writes a clock into every move
    # ({[%clk 0:00:59.9]}), and "59." reads as a move number to this regex.
    # Left in, this tier matched essentially every game in the archive.
    if LONG_GAME.search(movetext):
        return 5
    return 0


def movetext_of(pgn: str) -> str:
    """The movetext with comments removed — see tier()."""
    parts = pgn.split("\n\n", 1)
    return COMMENT.sub(" ", parts[1]) if len(parts) > 1 else ""


def fetch_archive(player: str, year: int, month: int) -> list:
    url = f"https://api.chess.com/pub/player/{player}/games/{year}/{month:02d}"
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(request, timeout=120) as response:
        return json.load(response).get("games", [])


def main() -> int:
    selected = []
    seen_urls = set()

    for player, year, month in ARCHIVES:
        try:
            games = fetch_archive(player, year, month)
        except urllib.error.HTTPError as error:
            print(f"# {player} {year}-{month:02d}: HTTP {error.code}", file=sys.stderr)
            continue

        candidates = []
        for game in games:
            pgn = game.get("pgn") or ""
            url = game.get("url") or ""
            if not pgn or url in seen_urls:
                continue
            rank = tier(pgn, movetext_of(pgn))
            if rank:
                candidates.append((rank, url, pgn))

        # Rarest first, then by url so a rerun over an unchanged archive is stable.
        candidates.sort(key=lambda c: (c[0], c[1]))
        for rank, url, pgn in candidates[:PER_ARCHIVE_CAP]:
            seen_urls.add(url)
            selected.append((rank, url, pgn))

        print(
            f"# {player} {year}-{month:02d}: {len(games)} games, "
            f"{len(candidates)} candidates",
            file=sys.stderr,
        )
        time.sleep(1)  # chess.com asks for serial requests.

    selected.sort(key=lambda c: (c[0], c[1]))
    selected = selected[:TOTAL_CAP]

    by_tier = {}
    for rank, _, _ in selected:
        by_tier[rank] = by_tier.get(rank, 0) + 1
    print(f"# selected {len(selected)} games by tier: {by_tier}", file=sys.stderr)

    for _, _, pgn in selected:
        sys.stdout.write(pgn.replace("\r\n", "\n").rstrip("\n"))
        sys.stdout.write("\n\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
