#include "domains/games/apis/one_d4_worker/occurrence_writer.h"

#include <optional>
#include <string>

#include "domains/games/libs/chess_cpp/pgn.h"

namespace one_d4_worker {
namespace {

constexpr char kLockGame[] =
    "SELECT game_url FROM game_features WHERE game_url = $1 ORDER BY game_url FOR UPDATE";

constexpr char kDeleteOccurrences[] =
    "DELETE FROM motif_occurrences WHERE game_url = $1 RETURNING id";

// The id is a VARCHAR(36) holding a UUID, generated by the database rather
// than here so the C++ worker needs no UUID library to agree with the Java
// one on the column's shape.
constexpr char kInsertOccurrence[] = R"sql(
INSERT INTO motif_occurrences
    (id, game_url, motif, ply, side, move_number, description,
     moved_piece, attacker, target, is_discovered, is_mate, pin_type)
VALUES (gen_random_uuid()::text, $1, $2, $3::int, $4, $5::int, NULLIF($6, ''),
        NULLIF($7, ''), NULLIF($8, ''), NULLIF($9, ''), $10::boolean,
        $11::boolean, NULLIF($12, ''))
RETURNING id
)sql";

std::string Number(int value) { return std::to_string(value); }

std::string Bool(bool value) { return value ? "true" : "false"; }

std::string Or(const std::optional<std::string>& value) { return value.value_or(""); }

std::string PinTypeOf(const one_d4::MotifOccurrence& occurrence) {
  return occurrence.pin_type.has_value() ? std::string(one_d4::ToString(*occurrence.pin_type)) : "";
}

}  // namespace

absl::Status ReplaceOccurrences(pg::Transaction& tx, std::string_view game_url,
                                absl::Span<const one_d4::MotifOccurrence> occurrences) {
  const std::string url(game_url);

  const absl::StatusOr<pg::Result> locked = tx.Exec(kLockGame, {url});
  if (!locked.ok()) return locked.status();

  // Deleted before inserting because the upsert has no key to replace on:
  // motif_occurrences has no uniqueness beyond a random id, so a game looked
  // at twice would otherwise keep both copies. A game whose second look
  // found no motifs must still lose the rows it had.
  const absl::StatusOr<pg::Result> deleted = tx.Exec(kDeleteOccurrences, {url});
  if (!deleted.ok()) return deleted.status();

  for (const one_d4::MotifOccurrence& occurrence : occurrences) {
    const absl::StatusOr<pg::Result> inserted =
        tx.Exec(kInsertOccurrence,
                {url, std::string(one_d4::ToString(occurrence.motif)), Number(occurrence.ply),
                 std::string(chess_cpp::ToString(occurrence.side)), Number(occurrence.move_number),
                 occurrence.description, Or(occurrence.moved_piece), Or(occurrence.attacker),
                 Or(occurrence.target), Bool(occurrence.is_discovered), Bool(occurrence.is_mate),
                 PinTypeOf(occurrence)});
    if (!inserted.ok()) return inserted.status();
  }
  return absl::OkStatus();
}

}  // namespace one_d4_worker
