[package]
name = "wordchains-bin"
version = "0.1.3"
edition.workspace = true
rust-version.workspace = true

[features]
embedded-graph = []

[dependencies]
clap = { workspace = true, features = ["derive"] }
log = { workspace = true }
serde_json = { workspace = true }
simplelog = { workspace = true }
wordchains = { workspace = true }
