[package]
name = "mithril"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
axum = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
server_pal = {workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
wordchains = { workspace = true }
