load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "wordchains",
    srcs = [
        "src/graph.rs",
        "src/init.rs",
        "src/lib.rs",
        "src/model.rs",
        "src/sha.rs",
        "src/storage.rs",
    ],
    crate_name = "wordchains",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(),
)

rust_test(
    name = "test_wordchains_lib",
    size = "small",
    crate = ":wordchains",
)
