[package]
name = "server_pal"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
axum = { workspace = true }
tower-http = { workspace = true, features = ["full"] }
