load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library", "go_test")
load("//bazel/rules:oci.bzl", "linux_oci_go")

go_library(
    name = "log_shipper_lib",
    srcs = [
        "s3.go",
        "shipper.go",
        "sigv4.go",
    ],
    importpath = "github.com/muchq/moonbase/domains/platform/apps/log_shipper",
    visibility = ["//visibility:public"],
)

go_test(
    name = "log_shipper_test",
    size = "small",
    srcs = [
        "s3_test.go",
        "shipper_test.go",
        "sigv4_test.go",
    ],
    embed = [":log_shipper_lib"],
)

go_binary(
    name = "log_shipper",
    srcs = ["main/main.go"],
    visibility = ["//visibility:public"],
    deps = [":log_shipper_lib"],
)

linux_oci_go(bin_name = "log_shipper")
