[package]
name = "wordchains"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
clap = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
