[package]
name = "wordchains"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
readme.workspace = true

[dependencies]
base64ct = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
sha2 = { workspace = true }
simplelog = { workspace = true }
tracing = { workspace = true }
