package com.muchq.games.one_d4.engine.model;

public enum Motif {
  PIN,
  CROSS_PIN,
  FORK,
  SKEWER,
  ATTACK,
  DISCOVERED_ATTACK,
  DISCOVERED_CHECK,
  CHECK,
  CHECKMATE,
  PROMOTION,
  PROMOTION_WITH_CHECK,
  PROMOTION_WITH_CHECKMATE,
  BACK_RANK_MATE,
  SMOTHERED_MATE,
  ZUGZWANG,
  DOUBLE_CHECK,
  OVERLOADED_PIECE
}
