load("@io_bazel_rules_scala//scala:scala.bzl", "scala_binary")

scala_binary(
    name = "Tracer",
    srcs = ["Tracer.scala"],
    main_class = "com.muchq.scraphics.Tracer",
    deps = [
        "@third_party//org/slf4j:slf4j_api",
    ],
)
