load("@crates//:defs.bzl", "all_crate_deps")
load("@rules_rs//rs:rust_binary.bzl", "rust_binary")
load("@rules_rs//rs:rust_library.bzl", "rust_library")
load("@rules_rs//rs:rust_test.bzl", "rust_test")

rust_library(
    name = "imagine_lib",
    srcs = [
        "src/lib.rs",
        "src/processing.rs",
        "src/radius.rs",
        "src/storage.rs",
    ],
    crate_name = "imagine",
    visibility = ["//visibility:public"],
    deps = all_crate_deps(),
)

rust_binary(
    name = "imagine",
    srcs = [
        "src/main.rs",
    ],
    crate_name = "imagine",
    data = [
        "//domains/graphics/data:marbles",
    ],
    deps = all_crate_deps() + [":imagine_lib"],
)

rust_test(
    name = "test_imagine",
    size = "small",
    crate = ":imagine",
)
